server:
  port: 8083

spring:

  kafka:
    bootstrap-servers: localhost:29092
    template:
      default-topic: officeRoutes
    consumer:
      group-id: OfficeGroupId
      auto-offset-reset: latest

      application:
        ports:
          - name: "Temruk"
            x: 10
            y: 20
          - name: "Poti"
            x: 70
            y: 40
          - name: "Samsun"
            x: 50
            y: 80

